/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo e Guilherme
 */
public class TelaRepositorio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRepositorio.class.getName());

    private IndexadorPalavras indexador;
    private File diretorio;
    private Tela telaPrincipal;

    /**
     * Creates new form TelaRepositorio
     */
    public TelaRepositorio(Tela telaPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        this.telaPrincipal = telaPrincipal;
        this.indexador = new IndexadorPalavras(101);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonIndexar = new javax.swing.JButton();
        buttonSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Repositório selecionado aparecerá aqui");
        jTextField1.setEnabled(false);

        buttonIndexar.setText("Indexar");
        buttonIndexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIndexarActionPerformed(evt);
            }
        });

        buttonSelecionar.setText("Selecionar");
        buttonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonIndexar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(buttonSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(buttonIndexar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buttonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelecionarActionPerformed
        JFileChooser seletor = new JFileChooser();
        seletor.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (seletor.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            diretorio = seletor.getSelectedFile();
            jTextField1.setText(diretorio.getAbsolutePath());
        }
    }//GEN-LAST:event_buttonSelecionarActionPerformed

    private void buttonIndexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIndexarActionPerformed
        if (diretorio == null) {
            JOptionPane.showMessageDialog(this, "Selecione um diretório primeiro!");
            return;
        }

        try {
            indexador.indexarDiretorio(diretorio);

            // Salva o índice
            File arquivoIndice = new File("indice.idx");
            indexador.salvarIndice(arquivoIndice.getAbsolutePath());

            // Salva o diretório na tela principal
            telaPrincipal.salvarDiretorio(diretorio);
            telaPrincipal.setIndexador(indexador, diretorio);

            JOptionPane.showMessageDialog(this,
                    "Indexação concluída!\nO índice foi salvo em: " + arquivoIndice.getAbsolutePath());

            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonIndexarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIndexar;
    private javax.swing.JButton buttonSelecionar;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
