/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo e Guilherme
 */
public class Tela extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());
    private static final String INDICE_FILE = "indice.idx";
    private static final String DIRETORIO_FILE = "diretorio.dat";
    private IndexadorPalavras indexador = new IndexadorPalavras(WIDTH);
    private File diretorioSelecionado;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
        configurarListaHTML();
        carregarIndiceAutomaticamente();
    }

    public void setIndexador(IndexadorPalavras indexador, File diretorio) {
        this.indexador = indexador;
        this.diretorioSelecionado = diretorio;
    }

    /**
     * Método que "importa" algumas funcionalidades HTML para serem
     * posteriormente usadas na apresentação dos arquivos na AreaResultado.
     */
    private void configurarListaHTML() {
        AreaResultado.setCellRenderer(new DefaultListCellRenderer() {
            public java.awt.Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                label.setVerticalAlignment(JLabel.TOP);
                label.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
                return label;
            }
        });
    }

    /**
     * Carrega a última instancia na qual o indice .idx e seu diretorio foram
     * gerados de forma automatica, mesmo que o app tenha sido fechado.
     */
    private void carregarIndiceAutomaticamente() {
        File arquivoIndice = new File(INDICE_FILE);
        File arquivoDiretorio = new File(DIRETORIO_FILE);

        if (arquivoIndice.exists() && arquivoDiretorio.exists()) {
            try {
                // Carrega o índice
                IndexadorPalavras idx = new IndexadorPalavras(101);
                idx.carregarIndice(arquivoIndice.getAbsolutePath());
                this.indexador = idx;

                // Carrega o diretório
                try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(
                        new java.io.FileInputStream(arquivoDiretorio))) {
                    this.diretorioSelecionado = (File) ois.readObject();
                }

                JOptionPane.showMessageDialog(this,
                        "Índice e diretório carregados com sucesso.\nO programa está pronto para buscas.");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível carregar o índice salvo.\nNecessário reindexação.");
                e.printStackTrace();
            }
        }
    }

    /**
     * Salva o diretorio onde o arquivo .idx é salvo.
     *
     * @param diretorio
     */
    public void salvarDiretorio(File diretorio) {
        try (java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(
                new java.io.FileOutputStream(DIRETORIO_FILE))) {
            oos.writeObject(diretorio);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaPesquisa = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        buttonSelecDir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaResultado = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indexador de Palavras");

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonSelecDir.setText("Selecionar Diretório");
        buttonSelecDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelecDirActionPerformed(evt);
            }
        });

        AreaResultado.setEnabled(false);
        jScrollPane2.setViewportView(AreaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AreaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSelecDir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSelecDir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AreaPesquisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSelecDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelecDirActionPerformed
        TelaRepositorio tr = new TelaRepositorio(this);
        tr.setVisible(true);
    }//GEN-LAST:event_buttonSelecDirActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        String texto = AreaPesquisa.getText().trim();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite uma palavra para busca.");
            return;
        }

        // Verifica se o diretório está disponível
        if (diretorioSelecionado == null || !diretorioSelecionado.exists()) {
            JOptionPane.showMessageDialog(this,
                    "Diretório não disponível. Selecione um diretório válido.");
            return;
        }

        try {
            List<String> arquivos = indexador.buscarPalavrasLista(texto.toLowerCase().split("\\s+"));

            if (arquivos.isEmpty()) {
                AreaResultado.setListData(new String[]{
                    "<html><b>Nenhum resultado encontrado.</b></html>"
                });
                return;
            }

            java.util.ArrayList<String> blocos = new java.util.ArrayList<>();

            for (String nomeArquivo : arquivos) {
                File arq = new File(diretorioSelecionado, nomeArquivo);
                if (!arq.exists()) {
                    System.out.println("Arquivo não encontrado: " + arq.getAbsolutePath());
                    continue;
                }

                try (BufferedReader br = new BufferedReader(new FileReader(arq))) {
                    String titulo = br.readLine();
                    String ano = br.readLine();
                    String autor = br.readLine();
                    br.readLine();
                    br.readLine();

                    String resumo = br.readLine();
                    if (resumo == null) {
                        resumo = "";
                    }

                    String bloco = "<html><b>" + (titulo != null ? titulo.replace("Título: ", "") : "Sem título") + "</b><br>"
                            + "<i>" + resumo + "</i></html>";
                    blocos.add(bloco);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            if (blocos.isEmpty()) {
                AreaResultado.setListData(new String[]{
                    "<html><b>Arquivos encontrados, mas não foi possível carregar o conteúdo.</b></html>"
                });
            } else {
                AreaResultado.setListData(blocos.toArray(new String[0]));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaPesquisa;
    private javax.swing.JList<String> AreaResultado;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonSelecDir;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
